# Site settings
title: Pokemon Index 
description: A simple web page created for the purpose of testing. 
remote_theme: pages-themes/dinky@v0.2.0
plugins:
- jekyll-remote-theme

# Build settings
markdown: kramdown
